### ISSUE TITLE
How install and use your script?

### ISSUE THREAD

**Issue by Argorate** [uuksu/RPGMakerDecrypter#1]
There is no .exe, and use .bat file don't do anything for me, so how can I use your script?

**Comment by uuksu** [comment]
Hi! I Noticed that the binaries link was still pointing to my old website address. You should be now able to download binaries from [here](http://uuksu.fi/other/RPGMakerDecrypter) and then proceed by following usage guide in README. I've also updated download link to README.

Batch file (.bat) is for building the output package. This requires that binaries are build with Visual Studio with Release configuration before. This will then generate the same output package you can download from the link I provided to you.

If you have any other questions feel free to ask! If not I'll close this issue.

**Comment by Argorate** [comment]
Oh thx ! But I try use it and : "Something went wrong with reading or extraction. Archive is likely invalid or corrupted".

With another tool found on internet(rgssad - rgss2a - rgss3a decrypter.exe), I have another message "Error reading file, no RGSSAD HEADER"

but i'm sure the file is the original file of project ! It's possible to bypass header?

**Comment by uuksu** [comment]
There is always possibility that it is using somekind of custom method for encryption. Could you provide me the archive file so I could take a look of it and try to figure it out?

**Comment by Argorate** [comment]
I send you an email ! thx for your help !

**Comment by uuksu** [comment]
Closing this as Argorates game was encrypted with some other method and RPGMakerDecrypter can't really support it.
