### ISSUE TITLE
Pokemon Uranium decrypt problem

### ISSUE THREAD

**Issue by uuksu** [uuksu/RPGMakerDecrypter#10]
> Yo! 
> I'm so happy to see that a decompiler exists, unfortunately i have the same problem, i used it for pokemon uranium

_Originally posted by @POPOharicot in https://github.com/uuksu/RPGMakerDecrypter/issues/8#issuecomment-1614911261_

**Comment by uuksu** [comment]
Hey @POPOharicot!

I split your comment as a new issue. Could you provide me a link of the game you're trying to decrypt and describe the problem you're experiencing?

**Comment by POPOharicot** [comment]
here :https://pokemonuranium.co/ 
![Capture d’écran 2023-06-30 190002](https://github.com/uuksu/RPGMakerDecrypter/assets/52485868/4d9b0981-7d1d-42b5-82f7-5fcb416af3a9)

thank you for being quick

**Comment by POPOharicot** [comment]
it doesn't work either for the game: To the moon, same error "invalid output file" maybe it's because both games are rpg maker xp games

**Comment by uuksu** [comment]
Good news, this is pretty easy to fix. Just rename `Uranium.rgssad` to Game.rgssad and try again :) The decrypter tries to determinite the version of the archive from the filename and it just fails because it has a different. Maybe there could be a better way to determinite the version or at least there could be better error message.

Could you try that it works if you do the renaming and maybe test the To the moon with a same tactic if it has differently named RGSSAD file?

**Comment by POPOharicot** [comment]
OK, that was actually the problem, thank you very much.

**Comment by uuksu** [comment]
Great! Glad things worked out nicely. I'll close this issue now.
