### ISSUE TITLE
I can't decrypt Five nights at Fuckboy's 2 Final Mix

### ISSUE THREAD

**Issue by Wario3493** [uuksu/RPGMakerDecrypter#11]
**Link to download the game/archive you're unable to decrypt**
Link to game:https://gamejolt.com/games/five-nights-at-f-boy-s-2-final-mix/53421 

**Describe the problem**
No files that the decrypter can decompile
**Details (please complete the following information):**
Windows 

RPGMakerDecrypter.exe

**Screenshots**

**Comment by uuksu** [comment]
Hey.

It seems that there is no encryption on the game you asked help for. All you need is `Game.rvproj2`on the project root with a following line:

`RPGVXAce 1.00`

If you have RPG Maker VX Ace installed, just double click the file and the project should open.

I'm closing this issue as there nothing else for me to do.
