### ISSUE TITLE
.exe's dont work on Wine

### ISSUE THREAD

**Issue by MesaBlack** [uuksu/RPGMakerDecrypter#12]
![Screenshot 2023-08-11 9 45 59 AM](https://github.com/uuksu/RPGMakerDecrypter/assets/132141735/e31ae863-d614-4489-989c-652e9b7f9a5e)
![Screenshot 2023-08-11 9 45 53 AM](https://github.com/uuksu/RPGMakerDecrypter/assets/132141735/69bca959-7b5b-4c3c-a25d-a851bc089534)

**Comment by uuksu** [comment]
Hey!

I've never promised that they should work on Wine. If they do it's great, but they are not officially supported. You're free to use the CLI-version that works on Linux.

I'm closing this issue as there is nothing else for me to do about this.
