### ISSUE TITLE
problem with game.ini

### ISSUE THREAD

**Issue by Half-Time-Demon** [uuksu/RPGMakerDecrypter#14]
**Link to download the game/archive you're unable to decrypt**
Link to game:
https://disk.yandex.ru/d/eiDMD9nOvO_zEw

**Describe the problem**
![image](https://github.com/uuksu/RPGMakerDecrypter/assets/72053859/5b0e4c13-1101-4a6c-a22b-d523227651d0)

how I understand problem in game.ini :
![image](https://github.com/uuksu/RPGMakerDecrypter/assets/72053859/367b7cd7-707b-473d-989d-868947843939)

because by some reasons game have in system folder this dll file:
![image](https://github.com/uuksu/RPGMakerDecrypter/assets/72053859/09bf35e8-b273-4791-95ff-7e8ebed04a11)

how I understand program rewrite game.ini file:
![image](https://github.com/uuksu/RPGMakerDecrypter/assets/72053859/2416717f-fe70-428e-86f7-631e98996a4e)
![image](https://github.com/uuksu/RPGMakerDecrypter/assets/72053859/cb300775-aa9b-43fc-b09b-aa1fba5fc0e7)
![image](https://github.com/uuksu/RPGMakerDecrypter/assets/72053859/680b4ba6-4efd-40d0-81b6-fd7a9d4918fa)

how I think problem can be resolved: 
make function that checked if file game.ini if yes ignore the constant.
or check what file is in folder system get file name replace this in constant or something like that 

**Details (please complete the following information):**
 - OS: Windows
 - RPGMakerDecrypter version: [CLI/GUI]

**Screenshots**
![image](https://github.com/uuksu/RPGMakerDecrypter/assets/72053859/96f78940-0e3e-4650-98c1-b71373696991)

**Comment by uuksu** [comment]
Hey!

I see, you're using the original project path as the output path of the decryptor. I've never used it that way myself but I see that could be use case. I'll implement check that the .ini and project file is not overwritten if they already exist.

**Comment by uuksu** [comment]
This has been implemented in v2.0.14. Thank you!
