### ISSUE TITLE
problem with program after open it in vs studio

### ISSUE THREAD

**Issue by Half-Time-Demon** [uuksu/RPGMakerDecrypter#15]
**Describe the problem**
after open the project in vs studio some thing like that:
![image](https://github.com/uuksu/RPGMakerDecrypter/assets/72053859/7c450dd2-e55a-4616-9b5e-8f3b1c7a46fa)

don't doo anything or don't save any changes after that project stop working correctly. What I mean: when you start program after that and want to open file or doo something else ... program doo nothing not open file dialog and anything.

how I understand after open in this style vs code rewrite all event in to empty:
![image](https://github.com/uuksu/RPGMakerDecrypter/assets/72053859/d8f834ed-41a3-4fb1-9106-ee12751ca00c)

why: idk.
how to fix: idk.

**Details (please complete the following information):**
 - OS: Windows
 - RPGMakerDecrypter version: GUI

**Comment by uuksu** [comment]
Hey!

 I have no idea what to do about this as for me it's working just fine. This is a problem with your developement environment and it is out of scope of this project.
