### ISSUE TITLE
After decryption then you run the project RPG maker VX ace throw  worrninig

### ISSUE THREAD

**Issue by Half-Time-Demon** [uuksu/RPGMakerDecrypter#16]
**Link to download the game/archive you're unable to decrypt**
Link to game:
https://disk.yandex.ru/d/eiDMD9nOvO_zEw

**Describe the problem**
After decryption then you run the project RPG maker VX ace throw  warning:
![image](https://github.com/uuksu/RPGMakerDecrypter/assets/72053859/53cb2b52-1c49-47e2-8d5f-6293f3368ad4)

if click cancel : project don't open.

if click ok : project open but idk what changes it make's.

**Details (please complete the following information):**
 - OS: Windows
 - RPGMakerDecrypter version: GUI

**Comment by uuksu** [comment]
Hey!

I think this is related to #14 where you have extracted the game to the distribution directory. When you open the project file RPG Maker deleted the encrypted RGSSAD archive for what ever reason. You can fix this by extracting the archive to some other folder. Problems with RPG Maker are out of scope of this project.
