### ISSUE TITLE
GUI "Unhandled Exception"

### ISSUE THREAD

**Issue by marianxtq** [uuksu/RPGMakerDecrypter#17]
**Link to download the game/archive you're unable to decrypt**
Link to game: https://ari-games.com/games/mtmbarc.html

**Describe the problem**
I opened the .rgssad file and got the message "Unhandled exception has oocured in your application. If you click continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

Index was outside bounds of the array."

**Details (please complete the following information):**
 - OS: Windows
 - RPGMakerDecrypter version: GUI

**Screenshots**
cant provide because of how buggy my windows computer is

**Comment by Husky2490** [comment]
I'm on Linux using the CLI version and I'm also running into this issue.  After reviewing the log, I believe this line is the issue
https://github.com/uuksu/RPGMakerDecrypter/blob/73d36b9c244a8041f686ced095ce6de3b9068b99/RPGMakerDecrypter.Cli/Program.cs#L58

**Comment by Husky2490** [comment]
Looking at the git history, downgrading to v2.0.13 will get rid of the issue if I'm right about this
