### ISSUE TITLE
Unable to decrypt the first game of the hello charlotte series

### ISSUE THREAD

**Issue by NumanSadik** [uuksu/RPGMakerDecrypter#18]
**Link to download the game/archive you're unable to decrypt**
Link to game: (Demo of it)
https://store.steampowered.com/app/557630/Hello_Charlotte_EP2_Requiem_Aeternam_Deo/

**Describe the problem**
unable to decrypt it in the newer version of your cli. Succeeded in an older version of your cli version though.

**Details (please complete the following information):**
 - OS: Windows
 - RPGMakerDecrypter version: Cli

Error: System.Exception: Testing
   at RPGMakerDecrypter.Cli.Program.Main(String[] args)

**Comment by NumanSadik** [comment]
[v2.0.11](https://github.com/uuksu/RPGMakerDecrypter/tree/v2.0.11) can decrypt it

**Comment by uuksu** [comment]
Hey! I'm so sorry, I broke the whole CLI with my previous development with a error logging by leaving a temporary exception throwing that I was using for testing. I've fixed the issue, v2.0.15 should work normally.

Could you please verify and I'll close the issue once you've done so?

**Comment by NumanSadik** [comment]
yes it does work now, also while you are here i gotta mention that cli also does not export (or it does not overwrite the existing file?) a file from the encrypted archive.

(Game dir)\Graphics\System\Window.png 
![Original](https://github.com/uuksu/RPGMakerDecrypter/assets/68291382/afbb91fe-0fe9-411a-9aa1-f17389a52705)

Encrpted within rgss3a file
![Window](https://github.com/uuksu/RPGMakerDecrypter/assets/68291382/6434fa7d-d106-48d9-a11d-ce57ec3f90ff)

**Comment by uuksu** [comment]
I think overwrite will be fixed by merging #19. As this is not related to the original issue, I'll close this one now.
