### ISSUE TITLE
RPG Maker Decrypter is failing.

### ISSUE THREAD

**Issue by PedroAlc** [uuksu/RPGMakerDecrypter#2]
Good evening, I tried to use "RPG Maker Decrypter" in a rgss2a file but it returns the error "Archive is invalid or corrupted. Reading Failed." The file is "original" of the project and I believe that it could have been used some different encrypter in the project, I think in the area of scripts.
Can you verify that?

**Comment by uuksu** [comment]
Hey PedroAlc!

Usually the case with that error is exactly what you described. Archive might be decrypted with some another encryption technique or it uses non-common encryption key.

I can verify this if you can upload rgss2a file for me to analyze.

**Comment by PedroAlc** [comment]
Thank you. The file is from this link: https://drive.google.com/file/d/1lVZL5Lp1ZMVQ2gA2GB51YFIYgArVjVRz/view?usp=sharing

**Comment by uuksu** [comment]
I suspect that it uses somekind of custom encryption technique that encrypts the whole archive somehow. If common encryption key (0xDEADCAFE) would been changed it would still keep archive header (first 7 bytes spell out RGSSAD) but now it's nowhere to be found.

I'm sorry I can't help you more with this problem.
