### ISSUE TITLE
Basic Question about getting this project running

### ISSUE THREAD

**Issue by Aayush499** [uuksu/RPGMakerDecrypter#22]
I cloned your repo to my windows machine. How exactly do we get the "RPGMakerDecrypter-cli" command running? Do I need to add the project's binary files to the path first?

**Comment by Mario8433** [comment]
Hi, if you only want this project to run, I don't think you need to clone the repo. There are built .exe files that you can directly run in the releases section, right in the sidebar of the code tab :-)

**Comment by uuksu** [comment]
Hey! Exactly what @Mario8433 said. 

This is a advanced tool assuming that the user has basic understanding of terminal/commandline applications. I do not unfortunately wan't to be a techical support.

Hope you get it working!
