### ISSUE TITLE
Invalid Input File

### ISSUE THREAD

**Issue by Zanes** [uuksu/RPGMakerDecrypter#8]
I used this tool for some games and it worked perfectly well, but in a chinese XP game it says invalid input file.
![image](https://github.com/uuksu/RPGMakerDecrypter/assets/5352796/62555ba4-53b9-4afc-b9dc-3fedb3145dae)
Tried with both the GUI and command line

**Comment by uuksu** [comment]
Hey! Could you provide me the game files so I can debug what is the problem?

**Comment by uuksu** [comment]
Oopsie, I accidentally closed the issue, but it should be fine now.

**Comment by POPOharicot** [comment]
Yo! 
I'm so happy to see that a decompiler exists, unfortunately i have the same problem, i used it for pokemon uranium

**Comment by Zanes** [comment]
My bad, at the time I used another decompiler that worked and forgot. I'll close the issue now.

**Comment by uuksu** [comment]
Ok, thanks for reporting back.
